name: Android Fastlane With Firebase App Distribution Workflow

on: 
  push:
    branches:
      - mainbbb

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo code
      uses: actions/checkout@v3

    - name: Set Up Java 17
      uses: actions/setup-java@v3.12.0
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.3'
        channel: 'stable'

    - name: Setup Ruby 
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.3.7"
        bundler-cache: true
        working-directory: appointmentapp/android

    - name: Create Environment File
      run: |
        echo "API_SECRET_KEY=${{ secrets.API_SECRET_KEY }}" > .env

    - name: Build and Distribute APK
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        FIREBASE_APPLE_ID: ${{ secrets.FIREBASE_APPLE_ID }} 
        FIREBASE_ANDROID_ID: ${{ secrets.FIREBASE_ANDROID_ID }}
      run: bundle exec fastlane android app_distribution
      working-directory: appointmentapp/android
